CREATE TABLE `relationship` (
	`Host1` VARCHAR(50) NULL DEFAULT NULL,
	`Host2` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
SHOW CREATE TABLE `sinaweibo`.`relationship`;
SHOW CREATE TABLE `sinaweibo`.`tweets`;
SHOW CREATE TABLE `sinaweibo`.`relationship`;
SHOW CREATE TABLE `sinaweibo`.`information`;



CREATE TABLE `information` (
	`User_id` VARCHAR(50) NULL DEFAULT NULL,
	`NickName` VARCHAR(50) NULL DEFAULT NULL,
	`Gender` VARCHAR(50) NULL DEFAULT NULL,
	`Province` VARCHAR(50) NULL DEFAULT NULL,
	`City` VARCHAR(50) NULL DEFAULT NULL,
	`BriefIntroduction` VARCHAR(50) NULL DEFAULT NULL,
	`Birthday` VARCHAR(50) NULL DEFAULT NULL,
	`Num_Tweets` VARCHAR(50) NULL DEFAULT NULL,
	`Num_Follows` VARCHAR(50) NULL DEFAULT NULL,
	`Num_Fans` VARCHAR(50) NULL DEFAULT NULL,
	`SexOrientation` VARCHAR(50) NULL DEFAULT NULL,
	`Sentiment` VARCHAR(50) NULL DEFAULT NULL,
	`VIPlevel` VARCHAR(50) NULL DEFAULT NULL,
	`Authentication` VARCHAR(50) NULL DEFAULT NULL,
	`URL` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;


CREATE TABLE `tweets` (
	`weibo_id` VARCHAR(50) NULL DEFAULT NULL,
	`User_id` VARCHAR(50) NULL DEFAULT NULL,
	`Content` VARCHAR(50) NULL DEFAULT NULL,
	`Pubtime` VARCHAR(50) NULL DEFAULT NULL,
	`Coordinates` VARCHAR(50) NULL DEFAULT NULL,
	`Tools` VARCHAR(50) NULL DEFAULT NULL,
	`Likes` INT(11) NULL DEFAULT NULL,
	`Comments` INT(11) NULL DEFAULT NULL,
	`Transfers` INT(11) NULL DEFAULT NULL
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
